---
sudo: false
language: ruby
rvm:
  - 2.2.0
cache: bundler
before_script:
  - npm install
  - npm install -g bower
  - bower install
scripts:
  - grunt build
notifications:
  email: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master

