# Site settings
title: Berriart | Desarrollo web con software libre
email: alberto@berriart.com
description: Personal page of Alberto Varela a Full Stack Web Developer based in Bilbao.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.berriart.com" # the base hostname & protocol for your site
main_navigation:
- text: Home
  url: /
- text: Projects
  url: /projects/
- text: Blog
  url: /blog/
- text: About me
  url: /alberto-varela/
permalink: /blog/:year/:month/:title/
paginate: 10
paginate_path: "/blog/page:num/"
twitter_username: artberri

# Build settings
markdown: kramdown

exclude: [
    'berriart-foundation',
    'javascript',
    'vendor',
    'bower_components',
    'node_modules',
    'Gruntfile.js',
    'Gemfile',
    'Gemfile.lock',
    'bower.json',
    'package.json',
    'scripts',
    'Rakefile',
    'Readme.md',
    '.scss-lint.yml',
    'eslint.json'
]

sass:
    style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
