# Site settings
title: Berriart
email: alberto@berriart.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.berriart.com" # the base hostname & protocol for your site
main_navigation:
- text: Home
  url: /
- text: Projects
  url: /projects/
- text: Contact
  url: /contact/
footer_navigation:
- text: Home
  url: /
- text: Projects
  url: /projects/
- text: Contact
  url: /contact/

# Build settings
markdown: kramdown

exclude: [
    'berriart-foundation',
    'javascript',
    'vendor',
    'bower_components',
    'node_modules',
    'Gruntfile.js',
    'Gemfile',
    'Gemfile.lock',
    'bower.json',
    'package.json',
    'scripts',
    'Rakefile',
    'Readme.md'
]

sass:
    style: compressed

gems:
  - jekyll-sitemap
